### PR TITLE
Feature/file structure

### PR DESCRIPTION
**Pull request by cieragrace**
Description:

I did this thing....

Neccesary checkmarks:

    [] All Tests are Passing

    [X] The code will run locally

Type of change

    [X] New feature
    [] Bug Fix

Implements/Fixes:
Added component folder and files

    description closes #

Check the correct boxes

    [X] This broke nothing
    [] This broke some stuff
    [] This broke everything

Testing Changes

    [X] No Tests have been changed
    [] Some Tests have been changed
    [] All of the Tests have been changed(Please describe what in the world happened)

Checklist:

    [X] My code has no unused/commented out code
    [X] I have reviewed my code
    [] I have commented my code, particularly in hard-to-understand areas
    [] I have fully tested my code

### CODE REVIEW

**Review by AnnaPete — APPROVED** [review]
We'll add the api calls file in the next one

**Comment by Abekomon** [comment]
Structure looks good!

**Comment by jaysmith2022** [comment]
Looks great! Just need to add the api calls folder later.

**Review by jaysmith2022 — COMMENTED** [review]
looks great. Just need to add the api calls folder!

**Review by Abekomon — APPROVED** [review]
Structure looks good!

**Pull request merged**
