### PR TITLE
Feature/favorites page

### PR DESCRIPTION
**Pull request by Abekomon**
Description:

Added a favorites route to App, at /favorites , 
Updated componentDidMount in app to include an id identifier,
Added 'addFavorite' method to App passed through props that adds a question to the 'favorites' state based on unique ID, 
Added links to '/favorites' and home page that switch between the two views,
Implemented minor styling to '/favorites' page

Necessary checkmarks:

    [] All Tests are Passing

    [x] The code will run locally

Type of change

    [x] New feature
    [x] Bug Fix

Implements/Fixes:

  * "As a user, I should be able to favorite a question and add it to a separate page to view later."

Check the correct boxes

    [x] This broke nothing
    [] This broke some stuff
    [] This broke everything

Testing Changes

    [x] No Tests have been changed
    [] Some Tests have been changed
    [] All of the Tests have been changed(Please describe what in the world happened)

Checklist:

    [x] My code has no unused/commented out code
    [x] I have reviewed my code
    [] I have commented my code, particularly in hard-to-understand areas
    [] I have fully tested my code

### CODE REVIEW

**Review by jaysmith2022 — APPROVED** [review]
We made some great progress. I see that we got the link working to our favorites and we are not able to add duplicates. This is a great headstart. Next in line is getting the delete functionality to work. Great work!

**Review by cieragrace — COMMENTED** [review]
Good thought bringing the id to the main state rather than in the question component. We can talk through the delete functionality and how to adjust the button in favorites on Monday. We can add in Jordan's typescript adjustments Monday as well. I think this is a great start.

**Review by AnnaPete — APPROVED** [review]
It was a good idea to change the id to the index instead of Date.now(). We might also want to look into prop interfaces

**Comment by cieragrace** [comment]
It is exciting to think we could have all this additional time to get to our extentions

**Pull request merged**
